name: GameCI

on:
  push:
    branches: [master]
  pull_request_target: {}
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: project-for-test
      - uses: actions/checkout@v4
        with:
          path: Packages/com.anatawa12.avatar-optimizer
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: anatawa12/sh-actions/setup-vrc-get@master
        # lock 3.4.2 for now for unity 2022.
        # see https://github.com/anatawa12/vrc-get/issues/262
      - run: vrc-get i --yes com.vrchat.avatars 3.4.2
      - uses: anatawa12/sh-actions/resolve-vpm-packages@master
        with:
          repos: |
            https://vpm.anatawa12.com/vpm.json

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: Library-

      - uses: game-ci/unity-test-runner@v3
        id: gameci
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_V3 }}
        with:
          testMode: EditMode
          githubToken: ${{ github.token }}
          coverageOptions: generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+com.anatawa12.avatar-optimizer.*
          customParameters: -nographics -assemblyNames com.anatawa12.avatar-optimizer.test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results
          path: ${{ steps.gameci.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.gameci.outputs.coveragePath }}
